extern const GeoLayout sl_area_1_geo[];
extern const GeoLayout sl_area_1[];
extern const Collision sl_area_1_collision[];
extern const MacroObject sl_area_1_macro_objs[];
extern Vtx sl_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_Plane_mesh_layer_1_vtx_0[4];
extern Gfx sl_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_sl_dl_f3dlite_material[];
extern Gfx mat_revert_sl_dl_f3dlite_material[];
extern Gfx sl_dl_Plane_mesh_layer_1[];
extern Gfx sl_dl_final_revert_mesh_layer_1[];
