extern const GeoLayout barrier_geo[];
extern u8 barrier_KKIIDDZZ_DAT_964__p00_ci8[];
extern u8 barrier_KKIIDDZZ_DAT_964__p00_pal_rgba16[];
extern u8 barrier_KKIIDDZZ_DAT_1380__p00_ci8[];
extern u8 barrier_KKIIDDZZ_DAT_1380__p00_pal_rgba16[];
extern Vtx barrier_barrier_mesh_layer_1_vtx_cull[8];
extern Vtx barrier_barrier_mesh_layer_1_vtx_0[8];
extern Gfx barrier_barrier_mesh_layer_1_tri_0[];
extern Vtx barrier_barrier_mesh_layer_1_vtx_1[16];
extern Gfx barrier_barrier_mesh_layer_1_tri_1[];
extern Gfx mat_barrier_f3dlite_material[];
extern Gfx mat_revert_barrier_f3dlite_material[];
extern Gfx mat_barrier_f3dlite_material_001[];
extern Gfx mat_revert_barrier_f3dlite_material_001[];
extern Gfx barrier_barrier_mesh_layer_1[];
extern Gfx barrier_final_revert_mesh_layer_1[];
