extern const GeoLayout castle_inside_area_1_geo[];
extern const GeoLayout castle_inside_area_1[];
extern const Collision castle_inside_area_1_collision[];
extern const MacroObject castle_inside_area_1_macro_objs[];
extern Vtx castle_inside_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx castle_inside_dl_Plane_mesh_layer_1_vtx_0[4];
extern Gfx castle_inside_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_castle_inside_dl_f3dlite_material[];
extern Gfx mat_revert_castle_inside_dl_f3dlite_material[];
extern Gfx castle_inside_dl_Plane_mesh_layer_1[];
extern Gfx castle_inside_dl_final_revert_mesh_layer_1[];
