extern const GeoLayout water_ball_geo[];
extern u8 water_ball_ci4_sophie_water3_ci4[];
extern u8 water_ball_ci4_sophie_water3_pal_rgba16[];
extern Vtx water_ball_Water_Ball_mesh_layer_1_vtx_cull[8];
extern Vtx water_ball_Water_Ball_mesh_layer_1_vtx_0[1984];
extern Gfx water_ball_Water_Ball_mesh_layer_1_tri_0[];
extern Gfx mat_water_ball_water[];
extern Gfx mat_revert_water_ball_water[];
extern Gfx water_ball_Water_Ball_mesh_layer_1[];
extern Gfx water_ball_final_revert_mesh_layer_1[];
